version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=siemensecommercedbnov2024
      - MYSQL_DATABASE=siemensqaecommercedbnov2024
      - MYSQL_DATABASE=siemenstestecommercedbnov2024
      - MYSQL_DATABASE=siemensprodecommercedbnov2024

    volumes:
      - /data/mysql
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
    #networks:
      #- boanetwork
  registration-api:
    image: registrationapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 9060-9070:7072
        - 7072:7072
    volumes:
      - /data/compose-app
    #networks:
      #- boanetwork   
    

### put all the networks here
#networks:
  #boanetwork:
networks:
  default:
    external:
      name: siemensnetwork

  