server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: REGISTRATIONAPI
          uri: lb://REGISTRATIONAPI
          predicates:
            - Path=/swagger-ui.html, /v3/api-docs/**, /swagger-ui/**
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"


